# Generated by Django 3.0.6 on 2020-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_auto_20170411_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('title', models.CharField(max_length=50, verbose_name='Title', blank=True)),
                ('description', models.CharField(max_length=1000, verbose_name='Description', blank=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='mezzanine_file_collections.MediaLibrary')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('page_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False,  to='pages.Page', on_delete=django.db.models.deletion.CASCADE, )),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Media Library',
                'verbose_name_plural': 'Media Libraries',              
            },
            bases=('pages.page', models.Model),
        ),
    
    ]
